/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.QuanLyNhaCungCapBUS;
import DAO.QuanLyNhaCungCapDAO;
import DTO.NhaCungCap;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Gyn
 */
public class Provide_Manager extends javax.swing.JFrame {
        QuanLyNhaCungCapBUS qlnccBUS;
    /**
     * Creates new form Provide_Manager
     */
    public Provide_Manager() {
        initComponents();
        qlnccBUS = new QuanLyNhaCungCapBUS();
        loadModal();
        tfMaNCC.setText(qlnccBUS.setMaNCC());
    }

    public void loadModal() {
        DefaultTableModel model = new DefaultTableModel();

        if(model.getRowCount()==0) {
            model = new DefaultTableModel(qlnccBUS.getHeaders(),0);
        }
        qlnccBUS.readDB();
        for(NhaCungCap ncc : qlnccBUS.getDsncc()) {
            Vector rowData = new Vector();
            rowData.add(ncc.getMaNCC());
            rowData.add(ncc.getTenNCC());
            rowData.add(ncc.getEmail());
            rowData.add(ncc.getDiaChi());
            rowData.add(ncc.getSDT());


            model.addRow(rowData);
        }
        tableNCC.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        NCCPanel = new javax.swing.JPanel();
        NCCContentPanel = new javax.swing.JPanel();
        NCCFillterPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btnLoc = new javax.swing.JButton();
        NCCInputPanel = new javax.swing.JPanel();
        tfDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenNCC = new javax.swing.JTextField();
        tfMaNCC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NCCButtonPanel = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNCC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhà cung cấp");
        setResizable(false);

        jTabbedPane2.setBackground(new java.awt.Color(0, 153, 255));

        NCCFillterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc"));

        jLabel16.setText("Mã NCC:");

        jLabel17.setText("Tên NCC:");

        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8_search_20px_1.png"))); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLocMouseClicked(evt);
            }
        });
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NCCFillterPanelLayout = new javax.swing.GroupLayout(NCCFillterPanel);
        NCCFillterPanel.setLayout(NCCFillterPanelLayout);
        NCCFillterPanelLayout.setHorizontalGroup(
            NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCFillterPanelLayout.createSequentialGroup()
                .addGroup(NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NCCFillterPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NCCFillterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCFillterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7))))
                    .addGroup(NCCFillterPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NCCFillterPanelLayout.setVerticalGroup(
            NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCFillterPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NCCFillterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoc)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        NCCInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhà cung cấp"));

        tfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaChiActionPerformed(evt);
            }
        });

        jLabel6.setText("Địa chỉ:");

        jLabel5.setText("Email:");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        tfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSDTActionPerformed(evt);
            }
        });

        jLabel4.setText("SĐT:");

        jLabel3.setText("Tên NCC:");

        tfTenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenNCCActionPerformed(evt);
            }
        });

        tfMaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNCCActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã NCC:");

        javax.swing.GroupLayout NCCInputPanelLayout = new javax.swing.GroupLayout(NCCInputPanel);
        NCCInputPanel.setLayout(NCCInputPanelLayout);
        NCCInputPanelLayout.setHorizontalGroup(
            NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCInputPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCInputPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NCCInputPanelLayout.createSequentialGroup()
                            .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(NCCInputPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCInputPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCInputPanelLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCInputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        NCCInputPanelLayout.setVerticalGroup(
            NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NCCInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NCCButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8_maintenance_20px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8_add_20px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8_cancel_20px.png"))); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8_restart_20px_1.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NCCButtonPanelLayout = new javax.swing.GroupLayout(NCCButtonPanel);
        NCCButtonPanel.setLayout(NCCButtonPanelLayout);
        NCCButtonPanelLayout.setHorizontalGroup(
            NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCButtonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(24, 24, 24))
        );
        NCCButtonPanelLayout.setVerticalGroup(
            NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCButtonPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(NCCButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnReset))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NCCContentPanelLayout = new javax.swing.GroupLayout(NCCContentPanel);
        NCCContentPanel.setLayout(NCCContentPanelLayout);
        NCCContentPanelLayout.setHorizontalGroup(
            NCCContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NCCContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NCCButtonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NCCFillterPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NCCInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NCCContentPanelLayout.setVerticalGroup(
            NCCContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCContentPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(NCCInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NCCButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NCCFillterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tableNCC.setAutoCreateRowSorter(true);
        tableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNCC.setShowHorizontalLines(true);
        tableNCC.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tableNCC);

        javax.swing.GroupLayout NCCPanelLayout = new javax.swing.GroupLayout(NCCPanel);
        NCCPanel.setLayout(NCCPanelLayout);
        NCCPanelLayout.setHorizontalGroup(
            NCCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NCCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NCCContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        NCCPanelLayout.setVerticalGroup(
            NCCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NCCContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NCCPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Nhà cung cấp", NCCPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaNCCActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String makh = tfMaNCC.getText().trim();
        String tenkh = tfTenNCC.getText().trim();
        String email = tfEmail.getText().trim();
        String diachi = tfDiaChi.getText().trim();
        String sdt = tfSDT.getText().trim();
        NhaCungCap ncc = new NhaCungCap(makh, tenkh, email, diachi, sdt);
        if (qlnccBUS.themNhaCungCap(ncc)) {
            JOptionPane.showMessageDialog(null,"Thêm nhà cung cấp thành công");
            loadModal();
        }
        else {
            JOptionPane.showMessageDialog(null,"Thêm thất bại");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String mancc = tfMaNCC.getText().trim();
        if(qlnccBUS.xoaNhaCungCap(mancc)) {
            JOptionPane.showMessageDialog(null,"Xóa thành công");
            tfMaNCC.setText(qlnccBUS.setMaNCC());
            tfTenNCC.setText("");
            tfEmail.setText("");
            tfDiaChi.setText("");
            tfSDT.setText("");
            loadModal();
        }
        else {
            JOptionPane.showMessageDialog(null,"Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String makh = tfMaNCC.getText().trim();
        String tenkh = tfTenNCC.getText().trim();
        String email = tfEmail.getText().trim();
        String diachi = tfDiaChi.getText().trim();
        String sdt = tfSDT.getText().trim();
        Boolean check = qlnccBUS.updateNhaCungCap(makh, tenkh, email, diachi, sdt);
        if(check) {
            JOptionPane.showMessageDialog(null,"Cập nhật thông tin nhà cung cấp thành công");
            loadModal();
        }
        else {
            JOptionPane.showMessageDialog(null,"Cập nhật thông tin nhà cung cấp thất bại");

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfMaNCC.setText(qlnccBUS.setMaNCC());
        tfTenNCC.setText("");
        tfEmail.setText("");
        tfDiaChi.setText("");
        tfSDT.setText("");
        loadModal();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tfTenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenNCCActionPerformed

    private void tfSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSDTActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiaChiActionPerformed

    private void tableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNCCMouseClicked
        // TODO add your handling code here:
         int i = tableNCC.getSelectedRow();
        tfMaNCC.setText(tableNCC.getModel().getValueAt(i,0).toString());
        tfTenNCC.setText(tableNCC.getModel().getValueAt(i,1).toString());
        tfEmail.setText(tableNCC.getModel().getValueAt(i,2).toString());
        tfDiaChi.setText(tableNCC.getModel().getValueAt(i,3).toString());
        tfSDT.setText(tableNCC.getModel().getValueAt(i,4).toString());
    }//GEN-LAST:event_tableNCCMouseClicked

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:

        String tenncc = jTextField7.getText().trim();
        String mancc = jTextField6.getText().trim();
        if(!tenncc.equals("") && !mancc.equals("")) {
            DefaultTableModel resultModel = new DefaultTableModel();
            if (resultModel.getRowCount() == 0) {
                resultModel = new DefaultTableModel(qlnccBUS.getHeaders(), 0);
            }
            for (NhaCungCap ncc : qlnccBUS.search(tenncc,mancc)) {
                Vector rowData = new Vector();
                rowData.add(ncc.getMaNCC());
                rowData.add(ncc.getTenNCC());
                rowData.add(ncc.getEmail());
                rowData.add(ncc.getDiaChi());
                rowData.add(ncc.getSDT());

                resultModel.addRow(rowData);
            }
            tableNCC.setModel(resultModel);
        }
        else if(!tenncc.equals("")) {
            DefaultTableModel resultModel = new DefaultTableModel();
            if (resultModel.getRowCount() == 0) {
                resultModel = new DefaultTableModel(qlnccBUS.getHeaders(), 0);
            }
            for (NhaCungCap ncc : qlnccBUS.searchByName(tenncc)) {
                Vector rowData = new Vector();
                rowData.add(ncc.getMaNCC());
                rowData.add(ncc.getTenNCC());
                rowData.add(ncc.getEmail());
                rowData.add(ncc.getDiaChi());
                rowData.add(ncc.getSDT());

                resultModel.addRow(rowData);
            }
            tableNCC.setModel(resultModel);
        }
        else if(!mancc.equals("")) {
            DefaultTableModel resultModel = new DefaultTableModel();
            if (resultModel.getRowCount() == 0) {
                resultModel = new DefaultTableModel(qlnccBUS.getHeaders(), 0);
            }
            for (NhaCungCap ncc : qlnccBUS.searchByID(mancc)) {
                Vector rowData = new Vector();
                rowData.add(ncc.getMaNCC());
                rowData.add(ncc.getTenNCC());
                rowData.add(ncc.getEmail());
                rowData.add(ncc.getDiaChi());
                rowData.add(ncc.getSDT());

                resultModel.addRow(rowData);
            }
            tableNCC.setModel(resultModel);
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (Exception e) {
            System.out.println(e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Provide_Manager frame = new Provide_Manager();
                Menu menuFrame = new Menu();
                if(menuFrame.checkLogin()) {
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    menuFrame.setVisible(false);
                    menuFrame.dispose();
                } else {
                    frame.dispose();
                    menuFrame.setVisible(false);
                    menuFrame.dispose();
                    Login login = new Login();
                    login.setLocationRelativeTo(null);
                    login.setVisible(true);
                    login.pack();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NCCButtonPanel;
    private javax.swing.JPanel NCCContentPanel;
    private javax.swing.JPanel NCCFillterPanel;
    private javax.swing.JPanel NCCInputPanel;
    private javax.swing.JPanel NCCPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tableNCC;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMaNCC;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTenNCC;
    // End of variables declaration//GEN-END:variables

}
